IIS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView

urlpatterns = [
    path('', include('leagues.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('index', views.IndexView.as_view(), name='index'),
    path('login/', auth_views.LoginView.as_view(template_name='polls/login.html'), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('games/', views.GamesView.as_view(), name='games'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

polls/models.py
import datetime
from django.db import models
from django.utils import timezone


class Genre(models.Model):
    name = models.CharField(max_length=100, primary_key=True, help_text="Name of the genre of a game")
    acronym = models.CharField(max_length=10, blank=True, help_text="Game genre acronym")
    description = models.CharField(max_length=500, blank=True, help_text="Description of genre")

    def __str__(self):
        return "{0} ({1})".format(self.acronym, self.name)


class GameModeType(models.Model):
    name = models.CharField(max_length=100, primary_key=True, help_text="Name of game mode type")

    def __str__(self):
        return self.name


class GameMode(models.Model):
    name = models.CharField(max_length=100, primary_key=True, help_text="Name of the game mode")
    type = models.ForeignKey(GameModeType, on_delete=models.SET_NULL, null=True, blank=True,
                             help_text="General type of game mode")
    team_player_count = models.PositiveSmallIntegerField(default=5, null=True, blank=True,
                                                         help_text="Number of players in one team")

    def __str__(self):
        return self.name


class Game(models.Model):
    name = models.CharField('name of the game', max_length=100, unique=True)
    genre = models.ForeignKey(Genre, on_delete=models.SET_NULL, null=True, blank=True,
                              verbose_name='genre of the game')
    release_date = models.DateField('release date of the game', null=True, blank=True)
    image_url = models.URLField('game image url', max_length=500, blank=True)
    publisher = models.CharField('game publisher', max_length=200, blank=True)
    game_modes = models.ManyToManyField(GameMode, blank=True, verbose_name='available game modes')

    def __str__(self):
        return self.name


class Sponsor(models.Model):
    name = models.CharField(max_length=200, primary_key=True)

    def __str__(self):
        return self.name


class Tournament(models.Model):
    def end_date_default(self):
        return datetime.date.today() + datetime.timedelta(days=7)

    name = models.CharField('tournament name', max_length=200, primary_key=True)
    prize = models.PositiveIntegerField('tournament prize', null=True, blank=True,
                                        help_text='prize pool in dollars')
    opening_date = models.DateField('date of the tournament start', default=datetime.date.today)
    end_date = models.DateField('date of the tournament end', default=end_date_default)
    sponsors = models.ManyToManyField(Sponsor, through='Sponsorship')

    def __str__(self):
        return self.name


class Sponsorship(models.Model):
    SPONSORSHIP_TYPES = (
        ('MAIN', 'Main'),
        ('SIDE', 'Side'),
    )
    sponsor = models.ForeignKey(Sponsor, on_delete=models.CASCADE)
    tournament = models.ForeignKey(Tournament, on_delete=models.CASCADE)
    type = models.CharField('sponsorship type', max_length=4, choices=SPONSORSHIP_TYPES, default=SPONSORSHIP_TYPES[0])
    amount = models.PositiveIntegerField('donation amount', null=True, blank=True)


class Clan(models.Model):
    name = models.CharField(max_length=200, primary_key=True)
    founded = models.DateField('foundation date', default=datetime.date.today)
    country = models.CharField('country of origin', max_length=200, blank=True)
    games = models.ManyToManyField(Game, verbose_name='Games focused by the clan')

    def __str__(self):
        return self.name


class Team(models.Model):
    name = models.CharField(max_length=200, primary_key=True)
    founded = models.DateField('foundation date', default=datetime.date.today)
    active = models.BooleanField('activity status', default=True)
    game = models.ForeignKey(Game, on_delete=models.SET_NULL, null=True, blank=True,
                             verbose_name='Game focused by the team')
    clan = models.ForeignKey(Clan, on_delete=models.SET_NULL, null=True, blank=True,
                             verbose_name='Related clan')

    def __str__(self):
        return self.name


class Match(models.Model):
    beginning = models.DateTimeField('beginning of the match', default=timezone.now)
    duration = models.DurationField('duration of the match')
    game = models.ForeignKey(Game, on_delete=models.CASCADE, verbose_name='related game')
    game_mode = models.ForeignKey(GameMode, on_delete=models.CASCADE, verbose_name='game mode of the match')
    tournament = models.ForeignKey(Tournament, on_delete=models.CASCADE, null=True, blank=True,
                                   verbose_name='related tournament')
    team_1 = models.ForeignKey(Team, on_delete=models.CASCADE, related_name='matches_a',
                               verbose_name='first participating team')
    team_2 = models.ForeignKey(Team, on_delete=models.CASCADE, related_name='matches_b',
                               verbose_name='second participating team')
    winner = models.ForeignKey(Team, on_delete=models.CASCADE, related_name='matches_won', verbose_name='winning team')

    def __str__(self):
        return "Match ({0}): {1} vs {2}".format(self.id, self.team_1, self.team_2)


class Equipment(models.Model):
    EQUIPMENT_TYPES = (
        ('KEYBOARD', 'Keyboard'),
        ('MOUSE', 'Mouse'),
        ('MONITOR', 'Monitor'),
        ('MOUSE_PAD', 'Mouse pad'),
        ('HEADSET', 'Headset'),
    )
    name = models.CharField(max_length=200, primary_key=True)
    type = models.CharField('Kind of equipment', max_length=20, choices=EQUIPMENT_TYPES)
    manufacturer = models.CharField('Equipment manufacturer', max_length=200, blank=True)
    brand = models.CharField('Brand of equipment', max_length=200, blank=True)

    def __str__(self):
        return self.name


class Player(models.Model):
    nickname = models.CharField(max_length=50, primary_key=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    country = models.CharField('country of birth', max_length=200, blank=True)
    birth_date = models.DateField('date of birth', null=True, blank=True)
    equipment = models.ManyToManyField(Equipment, verbose_name='Equipment used by player')
    games = models.ManyToManyField(Game, verbose_name='Games focused by the player')
    teams = models.ManyToManyField(Team, verbose_name='Team memberships')
    clans = models.ManyToManyField(Clan, verbose_name='Clan memberships')
    matches = models.ManyToManyField(Match, verbose_name='Played matches')

    @property
    def full_name(self):
        return "%s %s".format(self.first_name, self.last_name)

    def __str__(self):
        return "{0} ({1})".format(self.nickname, self.full_name)


class Death(models.Model):
    match = models.ForeignKey(Match, on_delete=models.CASCADE, verbose_name='Related match')
    match_time = models.TimeField(default=timezone.now)
    victim = models.ForeignKey(Player, on_delete=models.CASCADE, related_name='deaths', verbose_name='Killed player')
    killer = models.ForeignKey(Player, on_delete=models.CASCADE, related_name='kills', null=True, blank=True,
                               verbose_name='Killer')


class Assist(models.Model):
    ASSISTANCE_TYPE = (
        ('HEALING', 'Damage'),
        ('DAMAGE', 'Healing'),
    )
    death = models.ForeignKey(Death, on_delete=models.CASCADE, verbose_name='Related death')
    player = models.ForeignKey(Player, on_delete=models.CASCADE, verbose_name='Assisting player')
    type = models.CharField('Type of assistance', max_length=20, choices=ASSISTANCE_TYPE)


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/forms.py
from django import forms
from django.forms import ModelForm
from polls.models import *


class CalendarWidget(forms.TextInput):
    def __init__(self):
        super().__init__(attrs={'class': 'date_picker'})

    class Media:
        js = (
            'polls/js/date_picker.js',
        )


class PlayerForm(ModelForm):
    class Meta:
        model = Player
        fields = ['nickname', 'first_name', 'last_name', 'country', 'birth_date']
        widgets = {
            'birth_date': CalendarWidget(),
        }


class GameForm(ModelForm):
    class Meta:
        model = Game
        fields = ['name', 'release_date', 'publisher', 'image_url', 'genre', 'game_modes']
        widgets = {
            'release_date': CalendarWidget()
        }


class NameForm(forms.Form):
    your_name = forms.CharField(label='Your name', max_length=100)

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic, View
from django.utils import timezone
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout

from .models import Question, Choice
from .forms import *


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('polls:games'))


class SignupView(View):
    template_name = "polls/signup.html"

    def post(self, request):
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return HttpResponseRedirect(reverse('polls:index'))
        else:
            return render(request, self.template_name, {'form': form})

    def get(self, request):
        form = UserCreationForm()
        return render(request, self.template_name, {'form': form})


class GamesView(generic.TemplateView):
    template_name = "polls/games.html"

    def get_form(self, request, form_class, prefix):
        data = request.POST if prefix in request.POST else None
        return form_class(data, prefix=prefix)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        games = Game.objects.all()
        context['game_list'] = games
        edit_forms = []
        for game in games:
            edit_forms.append(GameForm(instance=game, prefix='game_edit_' + str(game.id)))
        context['edit_forms'] = edit_forms
        context['game_form'] = GameForm(prefix='game_create')
        return context

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        context['game_form'] = GameForm(prefix='game_create')
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        if 'game_create' in request.POST:
            create_form = GameForm(request.POST, prefix='game_create')
            if create_form.is_bound and create_form.is_valid():
                game_name = create_form.cleaned_data['name']
                if not Game.objects.filter(name=game_name).exists():
                    # commit=False doesn't save new model object directly into the DB
                    # so we can do additional processing before storing it in the DB with save method of model object
                    game_object = create_form.save(commit=False)

                    # ... do additional processing

                    game_object.save()  # save object do DB
                    create_form.save_m2m()  # need to save relations manually with commit=False
                    return HttpResponseRedirect(reverse('polls:games'))
            context['game_form'] = create_form

        elif 'game_id' in request.POST:
            try:
                game = Game.objects.get(pk=request.POST['game_id'])
                edit_form = GameForm(request.POST, instance=game, prefix='game_edit_' + str(game.id))
                if edit_form.is_bound and edit_form.is_valid():
                    edit_form.save()
                    return HttpResponseRedirect(reverse('polls:games'))
                form_list = context['edit_forms']
                form_list[:] = [edit_form if x.instance == game else x for x in form_list]

            except Game.DoesNotExist as err:
                return None

        return render(request, self.template_name, context)


class IndexView(generic.ListView):
    template_name = 'polls/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        data = Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]
        context['latest_question_list'] = data
        context['form'] = NameForm()
        context['player'] = PlayerForm()
        return context

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]

    def post(self, request):
        form = NameForm(self.request.POST)
        if form.is_valid():
            print(form.cleaned_data)
            return HttpResponseRedirect(reverse('polls:index'))
        return render(request, self.template_name)


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

polls/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ question.question_text }}</title>
</head>
<body>
    <h1>{{ question.question_text }}</h1>

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
    <input type="submit" value="Vote">
    </form>
</body>
</html>

polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <script src="{% static 'polls/js/jquery-3.3.1.min.js' %}"></script>
    {{ player.media }}
    <title>Questions</title>
</head>
<body>

<link rel="stylesheet" type="text/css" href="{% static 'polls/css/style.css' %}">
{% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
            <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
<form action="{% url 'polls:index' %}" method="post">
    {% csrf_token %}
    <table>
        {{ player.as_table }}
    </table>
    {{ form }}
    <input type="submit" value="Submit">
</form>
</body>
</html>

polls/templates/polls/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Leagues|Login</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load staticfiles %}

    <script src="{% static 'polls/js/jquery-3.3.1.min.js'%}"></script>
    <link rel="stylesheet" href="{% static 'polls/css/w3.css' %}">
    <link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-blue-grey.css">
    <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Open+Sans'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Audiowide" >

    <style>
        html,body,h1,h2,h3,h4,h5 {font-family: "Open Sans", sans-serif}

        .logoText {
            font-family: 'Audiowide', cursive;
            text-shadow: 3px 3px 5px gray
        }
    </style>

    <script>
        $(document).ready(function(){
            let username = $('#id_username')
            if (username) {
                username.va
            }
        });
    </script>
</head>
<body>
    {% load widget_tweaks %}
    <div class="w3-container w3-content" style="max-width:600px">
        <div class="w3-card-4 w3-round-xlarge" style="margin-top:100px">
            <div class="w3-center"><br>
                <h1 class="logoText">Leagues</h1>
                <p>Please log in to access all features of <b>Leagues</b>!</p>

                {% if next %}
                    {% if user.is_authenticated %}
                        <p>Your account doesn't have access to this page. To proceed,
                        please login with an account that has access.</p>
                    {% else %}
                        <p>Please login to see this page.</p>
                    {% endif %}
                {% endif %}
            </div>

            <form method="post" class="w3-container" action="{% url 'polls:login' %}">
                {% csrf_token %}
                <div class="w3-section w3-border-top" style="padding-top: 20px">
                         {% if form.username.errors %}
                            <div class="w3-container w3-padding-16 w3-margin-bottom w3-red w3-round-large">
                                {{ form.username.errors }}
                            </div>
                        {% endif %}

                        {% if form.password1.errors %}
                            <div class="w3-container w3-padding-16 w3-margin-bottom w3-red w3-round-large">
                                {{ form.password1.errors }}
                            </div>
                        {% endif %}

                        {% if form.password2.errors %}
                            <div class="w3-container w3-padding-16 w3-margin-bottom w3-red w3-round-large">
                                {{ form.password2.errors }}
                            </div>
                        {% endif %}

                    <label><b>{{ form.username.label_tag }}</b></label>
                    {% render_field form.username class+="w3-input w3-border w3-margin-bottom" placeholder="Enter Username" value="test"%}
                    <label><b>{{ form.password.label_tag }}</b></label>
                    {% render_field form.password class+="w3-input w3-border" placeholder="Enter Password" value="test_password_123" %}
                    <input class="w3-button w3-block w3-green w3-section w3-padding" type="submit" value="Login">
                    <input type="hidden" name="next" value="{{ next }}">
                </div>
            </form>

            <div class="w3-container w3-border-top w3-padding-16 w3-light-grey">
                <span class="w3-right w3-padding w3-hide-small">Don't have <a href="{% url 'polls:signup' %}">account</a> yet?</span>
            </div>

        </div>
    </div>
</body>
</html>

polls/templates/polls/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ question.question_text }}</title>
</head>
<body>
    <h1>{{ question.question_text }}</h1>

    <ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
    </ul>

    <a href="{% url 'polls:detail' question.id %}">Vote again?</a>
</body>
</html>

polls/templates/polls/signup.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Leagues|SignUp</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% load staticfiles %}

        <script src="{% static 'polls/js/jquery-3.3.1.min.js'%}"></script>
        <link rel="stylesheet" href="{% static 'polls/css/w3.css' %}">
        <link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-blue-grey.css">
        <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Open+Sans'>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Audiowide" >
        <style>
            html,body,h1,h2,h3,h4,h5 {font-family: "Open Sans", sans-serif}

            .logoText {
                font-family: 'Audiowide', cursive;
                text-shadow:3px 3px 5px gray
            }

            .errorlist {
                margin-top: 0;
                margin-bottom: 0;
            }
        </style>
    </head>
    <body>
        {% load widget_tweaks %}
        <div class="w3-container w3-content" style="max-width:600px">
            <div class="w3-card-4 w3-round-xlarge" style="margin-top:100px">

                <div class="w3-center"><br>
                    <h1 class="logoText">Leagues</h1>
                    <p>Sign up to access all features of <b>Leagues</b>!</p>

                    {% if next %}
                        {% if user.is_authenticated %}
                            <p>Your account doesn't have access to this page. To proceed,
                            please login with an account that has access.</p>
                        {% else %}
                            <p>Please login to see this page.</p>
                        {% endif %}
                    {% endif %}
                </div>

                <form method="POST" class="w3-container" action="{% url 'polls:signup' %}">
                    {% csrf_token %}
                    <div class="w3-section w3-border-top" style="padding-top: 20px">
                        {% if form.username.errors %}
                            <div class="w3-container w3-padding-16 w3-margin-bottom w3-red w3-round-large">
                                {{ form.username.errors }}
                            </div>
                        {% endif %}

                        {% if form.password1.errors %}
                            <div class="w3-container w3-padding-16 w3-margin-bottom w3-red w3-round-large">
                                {{ form.password1.errors }}
                            </div>
                        {% endif %}

                        {% if form.password2.errors %}
                            <div class="w3-container w3-padding-16 w3-margin-bottom w3-red w3-round-large">
                                {{ form.password2.errors }}
                            </div>
                        {% endif %}

                        <label><b>{{ form.username.label_tag }}</b></label>
                        {% render_field form.username class+="w3-input w3-border w3-margin-bottom" placeholder="Enter Username" %}
                        <label><b>{{ form.password1.label_tag }}</b></label>
                        {% render_field form.password1 class+="w3-input w3-border w3-margin-bottom" placeholder="Enter Password" %}
                        <label><b>{{ form.password2.label_tag }}</b></label>
                        {% render_field form.password2 class+="w3-input w3-border" placeholder="Repeat Password" %}

                        <input class="w3-button w3-block w3-green w3-section w3-padding" type="submit" value="Sign up">
                        <input type="hidden" name="next" value="{{ next }}">
                    </div>
                </form>

                <div class="w3-container w3-border-top w3-padding-16 w3-light-grey">
                    <span class="w3-right w3-padding w3-hide-small">Already have a <a href="{% url 'polls:login' %}">account</a>?</span>
                </div>
            </div>
        </div>
    </body>
</html>