IIS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView

urlpatterns = [
    path('', include('leagues.urls')),
    path('admin/', admin.site.urls),
]

leagues/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView
from django.urls import reverse
from . import views

app_name = 'leagues'
urlpatterns = [
    path('', RedirectView.as_view(pattern_name='leagues:index', permanent=False)),
    path('index/', views.GamesView.as_view(), name='index'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('genre/<slug:slug>/', views.GenreDetailView.as_view(), name='genre_detail'),
    path('player/<slug:slug>/', views.PlayerDetailView.as_view(), name='player_detail'),
    path('team/<slug:slug>/', views.TeamDetailView.as_view(), name='team_detail'),
    path('clan/<slug:slug>/', views.ClanDetailView.as_view(), name='clan_detail'),
    path('game/<slug:slug>/', views.GameDetailView.as_view(), name='game_detail'),
    path('match/<pk>/', views.MatchDetailView.as_view(), name='match_detail'),
    path('games/', views.GamesView.as_view(), name='games'),
    path('social/', views.SocialView.as_view(), name='social'),
    path('settings/', views.SettingsView.as_view(), name='settings'),
    path('tournaments/', views.TournamentView.as_view(), name='tournaments'),
    path('tournament/<slug:slug>/', views.TournamentDetailView.as_view(), name='tournament_detail'),
    path('gamemode/<slug:slug>/', views.GameModeDetailView.as_view(), name='game_mode_detail')
]

polls/models.py
import datetime
from django.db import models
from django.utils import timezone


class Genre(models.Model):
    name = models.CharField(max_length=100, primary_key=True, help_text="Name of the genre of a game")
    acronym = models.CharField(max_length=10, blank=True, help_text="Game genre acronym")
    description = models.CharField(max_length=500, blank=True, help_text="Description of genre")

    def __str__(self):
        return "{0} ({1})".format(self.acronym, self.name)


class GameModeType(models.Model):
    name = models.CharField(max_length=100, primary_key=True, help_text="Name of game mode type")

    def __str__(self):
        return self.name


class GameMode(models.Model):
    name = models.CharField(max_length=100, primary_key=True, help_text="Name of the game mode")
    type = models.ForeignKey(GameModeType, on_delete=models.SET_NULL, null=True, blank=True,
                             help_text="General type of game mode")
    team_player_count = models.PositiveSmallIntegerField(default=5, null=True, blank=True,
                                                         help_text="Number of players in one team")

    def __str__(self):
        return self.name


class Game(models.Model):
    name = models.CharField('name of the game', max_length=100, unique=True)
    genre = models.ForeignKey(Genre, on_delete=models.SET_NULL, null=True, blank=True,
                              verbose_name='genre of the game')
    release_date = models.DateField('release date of the game', null=True, blank=True)
    image_url = models.URLField('game image url', max_length=500, blank=True)
    publisher = models.CharField('game publisher', max_length=200, blank=True)
    game_modes = models.ManyToManyField(GameMode, blank=True, verbose_name='available game modes')

    def __str__(self):
        return self.name


class Sponsor(models.Model):
    name = models.CharField(max_length=200, primary_key=True)

    def __str__(self):
        return self.name


class Tournament(models.Model):
    def end_date_default(self):
        return datetime.date.today() + datetime.timedelta(days=7)

    name = models.CharField('tournament name', max_length=200, primary_key=True)
    prize = models.PositiveIntegerField('tournament prize', null=True, blank=True,
                                        help_text='prize pool in dollars')
    opening_date = models.DateField('date of the tournament start', default=datetime.date.today)
    end_date = models.DateField('date of the tournament end', default=end_date_default)
    sponsors = models.ManyToManyField(Sponsor, through='Sponsorship')

    def __str__(self):
        return self.name


class Sponsorship(models.Model):
    SPONSORSHIP_TYPES = (
        ('MAIN', 'Main'),
        ('SIDE', 'Side'),
    )
    sponsor = models.ForeignKey(Sponsor, on_delete=models.CASCADE)
    tournament = models.ForeignKey(Tournament, on_delete=models.CASCADE)
    type = models.CharField('sponsorship type', max_length=4, choices=SPONSORSHIP_TYPES, default=SPONSORSHIP_TYPES[0])
    amount = models.PositiveIntegerField('donation amount', null=True, blank=True)


class Clan(models.Model):
    name = models.CharField(max_length=200, primary_key=True)
    founded = models.DateField('foundation date', default=datetime.date.today)
    country = models.CharField('country of origin', max_length=200, blank=True)
    games = models.ManyToManyField(Game, verbose_name='Games focused by the clan')

    def __str__(self):
        return self.name


class Team(models.Model):
    name = models.CharField(max_length=200, primary_key=True)
    founded = models.DateField('foundation date', default=datetime.date.today)
    active = models.BooleanField('activity status', default=True)
    game = models.ForeignKey(Game, on_delete=models.SET_NULL, null=True, blank=True,
                             verbose_name='Game focused by the team')
    clan = models.ForeignKey(Clan, on_delete=models.SET_NULL, null=True, blank=True,
                             verbose_name='Related clan')

    def __str__(self):
        return self.name


class Match(models.Model):
    beginning = models.DateTimeField('beginning of the match', default=timezone.now)
    duration = models.DurationField('duration of the match')
    game = models.ForeignKey(Game, on_delete=models.CASCADE, verbose_name='related game')
    game_mode = models.ForeignKey(GameMode, on_delete=models.CASCADE, verbose_name='game mode of the match')
    tournament = models.ForeignKey(Tournament, on_delete=models.CASCADE, null=True, blank=True,
                                   verbose_name='related tournament')
    team_1 = models.ForeignKey(Team, on_delete=models.CASCADE, related_name='matches_a',
                               verbose_name='first participating team')
    team_2 = models.ForeignKey(Team, on_delete=models.CASCADE, related_name='matches_b',
                               verbose_name='second participating team')
    winner = models.ForeignKey(Team, on_delete=models.CASCADE, related_name='matches_won', verbose_name='winning team')

    def __str__(self):
        return "Match ({0}): {1} vs {2}".format(self.id, self.team_1, self.team_2)


class Equipment(models.Model):
    EQUIPMENT_TYPES = (
        ('KEYBOARD', 'Keyboard'),
        ('MOUSE', 'Mouse'),
        ('MONITOR', 'Monitor'),
        ('MOUSE_PAD', 'Mouse pad'),
        ('HEADSET', 'Headset'),
    )
    name = models.CharField(max_length=200, primary_key=True)
    type = models.CharField('Kind of equipment', max_length=20, choices=EQUIPMENT_TYPES)
    manufacturer = models.CharField('Equipment manufacturer', max_length=200, blank=True)
    brand = models.CharField('Brand of equipment', max_length=200, blank=True)

    def __str__(self):
        return self.name


class Player(models.Model):
    nickname = models.CharField(max_length=50, primary_key=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    country = models.CharField('country of birth', max_length=200, blank=True)
    birth_date = models.DateField('date of birth', null=True, blank=True)
    equipment = models.ManyToManyField(Equipment, verbose_name='Equipment used by player')
    games = models.ManyToManyField(Game, verbose_name='Games focused by the player')
    teams = models.ManyToManyField(Team, verbose_name='Team memberships')
    clans = models.ManyToManyField(Clan, verbose_name='Clan memberships')
    matches = models.ManyToManyField(Match, verbose_name='Played matches')

    @property
    def full_name(self):
        return "%s %s".format(self.first_name, self.last_name)

    def __str__(self):
        return "{0} ({1})".format(self.nickname, self.full_name)


class Death(models.Model):
    match = models.ForeignKey(Match, on_delete=models.CASCADE, verbose_name='Related match')
    match_time = models.TimeField(default=timezone.now)
    victim = models.ForeignKey(Player, on_delete=models.CASCADE, related_name='deaths', verbose_name='Killed player')
    killer = models.ForeignKey(Player, on_delete=models.CASCADE, related_name='kills', null=True, blank=True,
                               verbose_name='Killer')


class Assist(models.Model):
    ASSISTANCE_TYPE = (
        ('HEALING', 'Damage'),
        ('DAMAGE', 'Healing'),
    )
    death = models.ForeignKey(Death, on_delete=models.CASCADE, verbose_name='Related death')
    player = models.ForeignKey(Player, on_delete=models.CASCADE, verbose_name='Assisting player')
    type = models.CharField('Type of assistance', max_length=20, choices=ASSISTANCE_TYPE)


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

leagues/templates/leagues/form_errors.html
{% if errors %}
  <div class="w3-container w3-padding-16 w3-margin-bottom w3-red w3-round-large formErrors">
    {% for key, value in errors.items %}
      {{ value }}
    {% endfor %}
  </div>
{% endif %}

leagues/templates/leagues/login.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Leagues|Login</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  {% load static %}

  <script src="{% static 'leagues/js/jquery-3.3.1.min.js' %}"></script>
  <link rel="stylesheet" href="{% static 'leagues/css/w3.css' %}">
  <link rel="stylesheet" href="{% static 'leagues/css/style.css' %}">
  <link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-blue-grey.css">
  <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Open+Sans'>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Audiowide">

  <style>
    html, body, h1, h2, h3, h4, h5 {
      font-family: "Open Sans", sans-serif
    }

    body {
      padding: 0;
    }
  </style>
</head>
<body>
{% load widget_tweaks %}
<div class="w3-content" style="width:450px">
  <div class="w3-card-4 w3-round-xlarge">
    <div class="w3-container w3-center"><br>
      <h1 class="logoText">Leagues</h1>
      <p>Please log in to access all features of <b>Leagues</b>!</p>

      {% if next %}
        {% if user.is_authenticated %}
          <p>Your account doesn't have access to this page. To proceed,
            please login with an account that has access.</p>
        {% else %}
          <p>Please login to see this page.</p>
        {% endif %}
      {% endif %}
    </div>

    <form method="post" class="w3-container" action="{% url 'leagues:login' %}">
      {% csrf_token %}
      <div class="w3-section w3-border-top" style="padding-top: 20px">
        {% include 'leagues/form_errors.html' with errors=form.errors %}

        <label><b>{{ form.username.label_tag }}</b></label>
        {% render_field form.username class+="w3-input w3-border w3-margin-bottom" placeholder="Enter Username" value="admin" %}
        <label><b>{{ form.password.label_tag }}</b></label>
        {% render_field form.password class+="w3-input w3-border" placeholder="Enter Password" value="admin" %}
        <input class="w3-button w3-block w3-green w3-section w3-padding" type="submit" value="Login">
        <input type="hidden" name="next" value="{{ next }}">
      </div>
    </form>

    <div class="w3-container w3-border-top w3-padding-16 w3-light-grey">
      <span class="w3-right w3-padding w3-hide-small">Don't have an <a
          href="{% url 'leagues:signup' %}">account</a> yet?</span>
    </div>

  </div>
</div>
</body>
</html>

leagues/templates/leagues/match_detail.html
{% extends 'leagues/base.html' %}
{% block title %}Match | {{ match.id }} {% endblock %}


{% block left_panel %}
  {% with side_bars_enabled=True %}
    {{ block.super }}
  {% endwith %}
{% endblock left_panel %}


{% block content %}
  <div class="w3-container w3-margin-bottom flex-container" style="flex: 2 1 0;">
    <div class="w3-card w3-round-large w3-white" style="flex: 1 1 auto;">
      <header>
        <ul class="section-bar" style="flex: 1 1 auto">
          <li onclick="showSection(event, 'info');" id="info_tab"
              class="section-tab w3-bottombar w3-hover-light-grey w3-padding">
            Informations
          </li>
          <li onclick="showSection(event, 'teams');" id="teams_tab"
              class="section-tab w3-bottombar w3-hover-light-grey w3-padding">
            Teams
          </li>
          <li onclick="showSection(event, 'statistics');" id="stat_tab"
              class="section-tab w3-bottombar w3-hover-light-grey w3-padding">
            Statistics
          </li>
        </ul>
      </header>

      <div id="info" class="w3-container w3-section section">

        <h4><b>Date:</b>
          {{ match.beginning|date:"j.n.Y" }}
        </h4>
        <h4><b>Time</b>
          {{ match.beginning|date:"G:m:s" }}
        </h4>

        <h4><b>Duration:</b>
          {% if match.in_progress %}
            In progress
          {% else %}
            {{ match.duration_fmt }}
          {% endif %}
        </h4>

        <h4><b>Tournament:</b>
          {% if match.tournament %}
            <a href="{% url 'leagues:tournament_detail' match.tournament.slug %} ">
              {{ match.tournament }}
            </a>
          {% else %}
            Not part of any tournament
          {% endif %}
        </h4>

        <h4><b>Game:</b>
          <a href="{% url 'leagues:game_detail' match.game.slug %} ">{{ match.game.name }}</a>
        </h4>

        <h4><b>Game mode:</b>
          <a href="{% url 'leagues:game_mode_detail' match.game_mode.slug %} ">{{ match.game_mode.name }}</a>
        </h4>

        <h4><b>Teams:</b>
          <a href="{% url 'leagues:team_detail' match.team_1.slug %} ">{{ match.team_1.name }}</a> vs
          <a href="{% url 'leagues:team_detail' match.team_2.slug %} ">{{ match.team_2.name }}</a>
        </h4>

        <h4><b>Winner:</b>
          {% if match.in_progress %}
            Not ended yet
          {% else %}
            <a href="{% url 'leagues:team_detail' match.winner.slug %} ">{{ match.winner.name }}</a>
          {% endif %}
        </h4>

      </div>

      <div id="teams" class="w3-container w3-section section">
        <h3>Participating teams</h3>
        <div class="pagedTable w3-card w3-round">
          <table class="w3-table w3-striped w3-bordered w3-hoverable">
            <thead>
            <tr class="">
              <th style="text-align: center;"><a href="{% url 'leagues:team_detail' teams.0.slug %} }">
                <h4 style="text-align: center; font-family: 'Audiowide', cursive;">{{ teams.0.name }}</h4>
              </a></th>
              <th style="text-align: center;"><h4>VS</h4></th>
              <th style="text-align: center;"><a href="{% url 'leagues:team_detail' teams.1.slug %} }">
                <h4 style="text-align: center; font-family: 'Audiowide', cursive;">{{ teams.1.name }}</h4>
              </a></th>
            </tr>
            </thead>

            <tbody id="team_rows">
            {% for player in players %}
              <tr>
                <td style="text-align: center;">
                  <a href="{% url 'leagues:player_detail' player.0.player.slug %}">
                    {{ player.0.player.nickname }}
                  </a>
                </td>
                <td></td>
                <td style="text-align: center;">
                  <a href="{% url 'leagues:player_detail' player.1.player.slug %}">
                    {{ player.1.player.nickname }}
                  </a>
                </td>
              </tr>
            {% endfor %}
            </tbody>
          </table>
        </div>
      </div>


      <div id="statistics" class="w3-container w3-section section">
        <h3>Statistics</h3>
        <div class="pagedTable w3-card w3-round">
          <table class="w3-table w3-striped w3-bordered w3-hoverable">
            <thead>
            <tr class="">
              <th>Match time</th>
              <th>Killer</th>
              <th>Victim</th>
              {% for i in assist_num %}
                <th>Assist{{ i }}</th>
              {% endfor %}
            </tr>
            </thead>

            <tbody id="stat_rows">
            {% for death in deaths %}
              <tr style="display: none;">
                <td>{{ death.match_time_fmt }}</td>
                <td>
                  <a href="{% url 'leagues:player_detail' death.killer.slug %}">
                    {{ death.killer.nickname }}
                  </a>
                </td>
                <td>
                  <a href="{% url 'leagues:player_detail' death.victim.slug %}">
                    {{ death.victim.nickname }}
                  </a>
                </td>
                {#              {% for i in assist_num %}#}
                {#                <td>Assist{{ i }}</td>#}
                {#              {% endfor %}#}
                {% for assist in death.assist_set.all %}
                  <td>
                    <a href="{% url 'leagues:player_detail' assist.player.slug %}">
                      {{ assist.player.nickname }}</a> [{{ assist.type }}]
                  </td>
                {% endfor %}
              </tr>
            {% endfor %}
            </tbody>
          </table>
          {% include 'leagues/table_footer.html' %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}

leagues/templates/leagues/player_detail.html
{% extends 'leagues/base.html' %}
{% block title %}Players | {{ player.nickname }} {% endblock %}


{% block scripts %}
  <script>
      function buttonClick(event, object_id, action) {
          let url = '{% url 'leagues:player_detail' player.slug %}';
          let data = {
              'action': action,
              'object_id': object_id
          };

          function callback(json) {
              console.log("test");
              if (json['has_clan_teams']) {
                  openDialog('Do you really wish to leave all clan\'s teams?',
                      new CallbackConfig([object_id, 'force_leave_clan']));
              } else {
                  location.reload();
              }
          }

          baseButtonClick(event, data, url, callback);
      }
  </script>
{% endblock %}

{% block left_panel %}
  {% with side_bars_enabled=True %}
    {{ block.super }}
  {% endwith %}
{% endblock left_panel %}


{% block content %}
  <div class="w3-container w3-margin-bottom flex-container" style="flex: 2 1 0;">
    <div class="w3-card w3-round-large w3-white" style="flex: 1 1 auto;">
      <header>
        <h1 style="text-align: center; font-family: 'Audiowide', cursive;">{{ player.nickname }}</h1>
        {% if player.clan %}
          <h4 style="text-align: center; font-family: 'Audiowide', cursive;">
            CLAN:
            <a href="{% url 'leagues:clan_detail' player.clan.slug %}"
               style="text-align: center; font-family: 'Audiowide', cursive;">
              {{ player.clan.name }}
            </a>
          </h4>
        {% endif %}
        <ul class="section-bar" style="flex: 1 1 auto">
          <li onclick="showSection(event, 'info');" id="info_tab"
              class="section-tab w3-bottombar w3-hover-light-grey w3-padding">
            Player info
          </li>
          <li onclick="showSection(event, 'teams');" id="teams_tab"
              class="section-tab w3-bottombar w3-hover-light-grey w3-padding">
            Teams
          </li>
          <li onclick="showSection(event, 'matches');" id="matches_tab"
              class="section-tab w3-bottombar w3-hover-light-grey w3-padding">
            Matches
          </li>
          <li onclick="showSection(event, 'stats');" id="stats_tab"
              class="section-tab w3-bottombar w3-hover-light-grey w3-padding">
            Statistics
          </li>
        </ul>
      </header>

      <div id="info" class="w3-container w3-section section" style="position: relative;">
        {% if user.is_authenticated and user.player == player %}
          <div>
            <button type="button" class="w3-round w3-green w3-button w3-margin-right green_button"
                    onclick="$('#{{ player_form.prefix }}').show()">
              Edit <i class="fas fa-edit"></i>
            </button>
            {% if player.clan %}
              <button class="w3-round w3-red w3-button red_button"
                      onclick="openDialog('Do you really wish to leave clan \'{{ player.clan.name }}\'',
                          new CallbackConfig([{{ player.clan.id }}, 'leave_clan']));">
                Leave clan
              </button>
            {% endif %}
          </div>
        {% endif %}

        {% if player.image_url %}
          <div class="w3-border w3-padding" style="float: right;">
            <img src="{{ player.image_url }}"
                 style="width:250px" alt="Avatar">
          </div>
        {% endif %}

        <!-- PLAYER INFO !-->
        <h4><b>First name:</b> {{ player.user.first_name }}</h4>
        <h4><b>Last name:</b> {{ player.user.last_name }}</h4>
        <h4><b>Age:</b> {{ player.age }}</h4>
        <h4><b>Birth date:</b> {{ player.birth_date|date:"j.n.Y" }}</h4>
        <h4><b>Country of origin:</b> {{ player.country.name }}</h4>
        <h4>
          <b>Description:</b>
        </h4>
        <article class="w3-container">
          <p style="margin:0;">{{ player.description }}</p>
        </article>
      </div>


      <div id="teams" class="w3-container w3-section section">
        <h3>Teams</h3>
        <div class="pagedTable w3-card w3-round">
          <table class="w3-table w3-striped w3-bordered w3-hoverable">
            <thead>
            <tr>
              <th>Name</th>
              <th>Leader</th>
              <th>Win ratio</th>
              {% if user.is_authenticated and user.player == player %}
                <th></th>
              {% endif %}
            </tr>
            </thead>

            <tbody id="team_rows">
            {% for team in player.teams.all %}
              <tr>
                <td>
                  <a href="{% url 'leagues:team_detail' team.slug %}">
                    {{ team.name }}
                  </a>
                </td>

                <td>
                  <a href="{% url 'leagues:player_detail' team.leader.slug %}">
                    {{ team.leader }}
                  </a>
                </td>

                <td>
                  {{ team.win_ratio }}
                </td>

                {% if user.is_authenticated and user.player == player %}
                  <td class="w3-padding-3 w3-small table_button_center">
                    <button onclick="openDialog('Do you really wish to leave team \'{{ team.name }}\'',
                        new CallbackConfig([{{ team.id }}, 'leave_team']));"
                            class="w3-button w3-red table_button red_button">
                      Leave
                    </button>
                  </td>
                {% endif %}
              </tr>
            {% endfor %}
            </tbody>
          </table>
          {% include 'leagues/table_footer.html' %}
        </div>
      </div>


      <div id="matches" class="w3-container w3-section section">
        <h3>Matches</h3>
        <div class="pagedTable w3-card w3-round">
          <table class="w3-table w3-striped w3-bordered w3-hoverable">
            <thead>
            <tr class="">
              <th>Team</th>
              <th>Winner</th>
              <th>Tournament</th>
              <th>Game</th>
              <th></th>
            </tr>
            </thead>

            <tbody id="stat_rows">
            {% for match in player.playedmatch_set.all %}
              <tr style="display: none">
                <td>
                  <a href="{% url 'leagues:team_detail' match.team.slug %}">
                    {{ match.team }}
                  </a>

                </td>
                <td>
                  <a href="{% url 'leagues:team_detail' match.match.winner.slug %}">
                    {{ match.match.winner }}
                  </a>
                </td>
                <td>
                  {% if match.match.tournament %}
                    <a href="{% url 'leagues:tournament_detail' match.match.tournament.slug %}">
                      {{ match.match.tournament }}
                    </a>
                  {% else %}
                    {{ match.match.tournament }}
                  {% endif %}
                </td>
                <td>{{ match.match.game }}</td>
                <td><a href="{% url 'leagues:match_detail' match.match.id %}"><i class="fa fa-eye"></i></a></td>
              </tr>
            {% endfor %}
            </tbody>
          </table>
          {% include 'leagues/table_footer.html' %}
        </div>
      </div>


      <div id="stats" class="w3-container w3-section section">
        <h3>Statistics</h3>
        <div class="pagedTable w3-card w3-round">
          <table class="w3-table w3-striped w3-bordered w3-hoverable">
            <thead>
            <tr class="">
              <th>Game</th>
              <th>K/D ratio</th>
              <th>Win ratio</th>
            </tr>
            </thead>

            <tbody id="stat_rows">
            {% for record in player_stats %}
              <tr style="display: none">
                <td>
                  <a href="{% url 'leagues:game_detail' record.0.slug %}">
                    {{ record.0.name }}
                  </a>
                </td>
                <td>{{ record.1 }}</td>
                <td>{{ record.2 }}</td>
              </tr>
            {% endfor %}
            </tbody>
          </table>
          {% include 'leagues/table_footer.html' %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}

{% block endpage %}
  {% load widget_tweaks %}

  <!--  PLAYER INFO FORM !-->
  {% if user.is_authenticated %}
    <div id="{{ player_form.prefix }}" class="w3-modal" {% if player_form.errors %}
         style="display: block" {% endif %}>
      <div class="w3-modal-content w3-card-4" style="max-width:600px">
        <header class="w3-container w3-center w3-light-grey w3-border-bottom">
          <h3 class="modalTitle">Edit '{{ player_form.nickname.value }}'</h3>

          <button onclick="$('#{{ player_form.prefix }}').hide()" type="button"
                  class="w3-button w3-display-topright w3-red">
            <i class="fa fa-times"></i>
          </button>
        </header>
        <form method="POST" action="{% url 'leagues:player_detail' player.slug %}">
          <div class="w3-section w3-container">
            {% csrf_token %}
            {% include 'leagues/form_errors.html' with errors=player_form.errors %}

            {{ player_form.user.as_hidden }}

            <label><b>{{ player_form.nickname.label_tag }}</b></label>
            {% render_field player_form.nickname class+="formUnique w3-input w3-border w3-margin-bottom" %}

            <div class="w3-margin-bottom input-flex">
              <div class="w3-margin-right" style="flex:1 0 0;">
                <label><b>{{ player_form.first_name.label_tag }}</b></label>
                {% render_field player_form.first_name class+="w3-input w3-border" %}
              </div>
              <div style="flex:1 0 0;">
                <label><b>{{ player_form.last_name.label_tag }}</b></label>
                {% render_field player_form.last_name class+="w3-input w3-border" %}
              </div>
            </div>

            <label><b>{{ player_form.country.label_tag }}</b></label>
            {% render_field player_form.country class+="w3-input w3-border w3-margin-bottom" %}

            <label><b>{{ player_form.birth_date.label_tag }}</b></label>
            <div class='w3-cell-row w3-margin-bottom'>
              {% render_field player_form.birth_date class+="w3-input w3-border w3-cell" %}
              <div class="w3-cell w3-cell-middle w3-center w3-border date_icon">
                <span class="fa fa-calendar"></span>
              </div>
            </div>

            <label><b>{{ player_form.image_url.label_tag }}</b></label>
            {% render_field player_form.image_url class+="w3-input w3-border w3-margin-bottom" %}

            <label><b>{{ player_form.description.label_tag }}</b></label>
            {% render_field player_form.description class+="w3-input w3-border" %}
          </div>

          <div class="w3-container w3-border-top w3-padding-16 w3-light-grey">
            <button onclick="$('#{{ player_form.prefix }}').hide()" type="button"
                    class="w3-button w3-red">Cancel
            </button>

            <input class="formAction" type="hidden" name="action" value="player_edit">
            <input class="formSubmit w3-button w3-green w3-right" type="submit" value="Edit">
          </div>
        </form>
      </div>
    </div>
  {% endif %}

{% endblock %}